### PR TITLE
Enhance UX to fix multi instance bug

### PR DESCRIPTION
**Pull request by theaubmov**
## Summary by CodeRabbit

- **New Features**
	- Improved handling of loop cardinality properties with enhanced user interface elements for BPMN diagrams.
	- Enhanced user control over input-output value relationships with a new output synchronization feature.
	- Introduced completion condition functionality with support for translations and command execution for an improved user experience.
	- Streamlined setting and management of input collections with added debounce and translation services.
	- Added functionality for managing input data items in a BPMN workflow.
	- Introduced a feature for synchronizing output elements with input elements in a BPMN properties panel.
	- Enhanced user control over setting and removing loop data output references in BPMN elements.

### CODE REVIEW

**Comment by burnettk** [comment]
what happens when "Output Element is Synchronized with Input Element" is checked?

**Comment by theaubmov** [comment]
When the Output Element and Input Element have the same value (variableName), BPMN-JS is unable to parse the Output Element value. The issue arises only if the user wants to use the same value for both the Input and Output Elements. That's why the new checkbox "Output Element is Synchronized with Input Element" has been added to allow users to achieve these use cases. This is not a BPMN spec, it's just a UI enhancement to address these issues.

**Comment by burnettk** [comment]
@essweine , did you discuss this one with ayoub? it is a valid use case to have a matching Output Element and Input Element in your opinion? you think we should get this change merged?

**Comment by essweine** [comment]
Yes, we discussed this.  It is definitely a valid use case..  However, I ran into a problem doing some testing.  I created a simple diagram (had to change the extension to upload) [multiinstance.txt](https://github.com/sartography/bpmn-js-spiffworkflow/files/15113390/multiinstance.txt) that uses two different collections, but when I reloaded it, the output item was lost and the "synchronize" box was checked..

Also, when I remove an output collection, the `loopOutputDataRef` gets set to `undefined`, which is going to cause runtime errors (this might be an existing bug, but we should go ahead and fix it).

The third problem I had was that there's an attribute `isOutputSynched` which doesn't have a namespace.  I wonder if we should add a namespace and not try to add the `outputDataItem` if it is checked (this would require a slight change to the library parser but it would be fairly trivial)?  It would also be better to put the attribute on `multiInstanceLoopCharacteristics` instead of the task.

**Comment by theaubmov** [comment]
Fixed the issue of getting an 'undefined' value when removing the output collection.

For isOutputSynched I added Spiffworkflow namespace,

When the user check the box of isOutputSync, the current behaviour is adding dataOutput item with same value of input item, so nothing in the backend will change. and for the point of adding isOutputSync attribute to multiInstance LoopCharacterisitcis and not element, it makes sense, but to do so we need to override the default bpmn moddle. so that's why it's still implemented at task level.

For the first issue of losing output element value with that example, I'm not able to regenerate it again by running only bpmn editor, @essweine could you please verify if the issue still exists after last changes.

To optimise the multi instance panel and make it more readable and easier to understand, Should we create a new ticket for it, where we define how the optimised version will look like?

**Comment by essweine** [comment]
> For the first issue of losing output element value with that example, I'm not able to regenerate it again by running only bpmn editor, @essweine could you please verify if the issue still exists after last changes.

I was unable to replicate this time either, so I think this is good to go.
> 
> To optimise the multi instance panel and make it more readable and easier to understand, Should we create a new ticket for it, where we define how the optimised version will look like?

I'm in favor of a separate ticket for that so we can finally get this merged.

**Pull request merged**
