### PR TITLE
In and Out Variables for Tasks

### PR DESCRIPTION
**Pull request by theaubmov**
This PR is about controlling data flow through tasks, making sure that tasks receive the right data (inputs) and produce expected results (outputs) that other parts of the process can use.

## Summary by CodeRabbit

- **New Features**
  - Introduced the ability to manage BPMN input/output variables in the properties panel, allowing users to add and delete input and output variables for user tasks and script tasks.

- **Style**
  - Adjusted padding and margins in the bio-properties panel for a more refined layout.

### CODE REVIEW

**Comment by burnettk** [comment]
i think there are a couple nitpicky copy exits suggested by coderabbit.

perhaps it would be worth demoing this one to the team?

**Comment by theaubmov** [comment]
@burnettk Except for the typing mistakes, the main point raised by Coderabbit is having some challenges locating some utils functions that exist at the level of the BPMN.js library, and we import them in our extensions, such as the is method that can be used to verify the type of an element. 

Do you mean these two points, or are there other suggestions I've missed?

**Comment by burnettk** [comment]
i just wanted you to take a look at them and see if they were worth fixing, you did it, thanks. 👍

**Comment by burnettk** [comment]
i guess there are some conflicts here now, @theaubmov since we stalled so long, sorry. are you worried about this change in general, or it's not too likely to break existing functionality? i just merged everything else, but this one scared me the most. i'd love to get it merged if you think it's good to go. thank you.

**Comment by theaubmov** [comment]
Yes, I got your concerns. I believe we can merge this change. The new feature is an extension to the editor and it won't impact or alter any existing features. The point of introducing in and out variables for tasks is to allow users to define input and output elements at the task level.

**Pull request merged**
