### PR TITLE
Feature/data store props

### PR DESCRIPTION
**Pull request by danfunk**

### CODE REVIEW

**Review by burnettk — APPROVED** [review]

**Comment by jbirddog** [comment]
I didn't see this, and may have missed it so if so please disregard - but with a data store ref there is a `dataStore` node that is a sibling to the process. This dataStore node has a name that maps to the class the backend provides to SpiffWorkflow and the id maps to the dataStoreRef. Any way just wanted to mention that and if its there all good bpmn-js is hard for me to follow.

Also in talking with Dan we likely want to configure these out of process items somewhere else and add the nodes needed right before the xml is executed (vs design time) which I do think has some interesting aspects.

**Comment by danfunk** [comment]
@theaubmov - can you add the dataStore to the xml as well - will need to be at the process level, per @jbirddog comment.  Then we can merge this and get it closed out.  this is tight work and well done.

**Comment by theaubmov** [comment]
@danfunk @jbirddog | I pushed new changes to add dataStore to the xml, with a test to check that dataStore has been added correctly to the process definition.

Screenshot 2023-11-22 115348

**Review by jbirddog — APPROVED** [review]
Looks really good. May be worth adding tests for things like adding the second ref to a data store (believe this case is handled in code), removing the second ref keeps the data store, removing the last ref removes the data store, etc. Cool if we do those as follow ups but there were similar issues with data objects if i recall which ended up as bugs.

**Comment by theaubmov** [comment]
Yes, good point, I saw those scenarios but I thought maybe to start handling the more obvious one like avoiding having two dataStores with the same ID, but you re correct, there's a missing part if the user deletes a datastore from a dataRef, and it's no longer in use, normally it should be deleted from the process too. Also might be usefull to show dataStores in the level of process for better visibility like the case with DataObjects, but that might be secondary.

**Comment by theaubmov** [comment]
@danfunk @jbirddog | I've made further changes with a test case to handle the deletion of the dataStore element in the event that it is not linked to a dataStore reference.

**Review by danfunk — COMMENTED** [review]
I'm going to go ahead and merge this and test it out with the app.

**Pull request merged**
